### PR TITLE
adding .msg support

### PR DESCRIPTION
**Pull request by deanmalmgren**
This is based off of the work in #17 using the new-style classes. I'd like to get the standardized text test to work by including a `.msg` file that has the subject line "the quick brown fox jumps over the lazy dog" with an empty body, but I'm having a little difficulty writing a `.msg` file. If anyone knows how to do this or has access to Outlook, I'd appreciate your help!

### CODE REVIEW

**Comment by mattgwwalker** [comment]
I have access to Outlook 2007.  Are you still in need of a test msg example?

**Comment by deanmalmgren** [comment]
That would be awesome if its easy for you. An email with the subject of
"the quick brown fox" and the contents of "jumps over the lazy dog" would
be really helpful. I don't really care who the recipient or senders are.
Thanks!

On Mon, Jun 22, 2015 at 4:41 PM Matthew Walker <notifications@github.com>
wrote:

> I have access to Outlook 2007. Are you still in need of a test msg example?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/deanmalmgren/textract/pull/87#issuecomment-114271961>.
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*

**Comment by mattgwwalker** [comment]
Hi Dean,

I've attached two msg files generated from Outlook 2007.  One is a default
and the other is a Unicode version.  ExtractMsg.py should handle both.

**Comment by deanmalmgren** [comment]
Dang. I don't think github is smart enough to handle attachments. Can you
send them to my email address: dean dot malmgren at datascopeanalytics.com?

Thanks!

On Mon, Jun 22, 2015 at 5:13 PM Matthew Walker <notifications@github.com>
wrote:

> Hi Dean,
>
> I've attached two msg files generated from Outlook 2007. One is a default
> and the other is a Unicode version. ExtractMsg.py should handle both.
>
> On 23 June 2015 at 09:53, Dean Malmgren <notifications@github.com> wrote:
>
> > That would be awesome if its easy for you. An email with the subject of
> > "the quick brown fox" and the contents of "jumps over the lazy dog" would
> > be really helpful. I don't really care who the recipient or senders are.
> > Thanks!
> >
> > On Mon, Jun 22, 2015 at 4:41 PM Matthew Walker <notifications@github.com
> >
> > wrote:
> >
> > > I have access to Outlook 2007. Are you still in need of a test msg
> > example?
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/deanmalmgren/textract/pull/87#issuecomment-114271961
> > >.
> > >
> > --
> > *dean malmgren | +1.312.884.9214 *
> > *partner, data scientist | datascope*
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/deanmalmgren/textract/pull/87#issuecomment-114275717
> >.
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/deanmalmgren/textract/pull/87#issuecomment-114284176>.
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*

**Pull request merged**
