### PR TITLE
Add additional Audio parsing method - Sphinx audio

### PR DESCRIPTION
**Pull request by barrust**
The [SpeechRecognition](https://github.com/Uberi/speech_recognition) library allows for using different extraction libraries and APIs. I need to be able to extract text from audio locally and possibly without internet access. To do so I added the ability to programmatically select which engine to use.
- Added engine parameter to audio.py extract method
  - Defaults to Google API extraction
- Updated required packages
- Updated required python packages
- Added tests for both Sphinx and Google for MP3 extraction
- Updated the documentation

Currently supports google and [CMU Sphinx](http://cmusphinx.sourceforge.net/) but should be mostly trivial to add others.

Tests worked using docker configuration.

### CODE REVIEW

**Comment by barrust** [comment]
After the change to libjpeg-dev I am still getting a build failure from travis-ci but it is for epub which wasn't touched in this PR. Is there an issue with epub? When running using the run_docker_test.sh I didn't get the error.

**Comment by deanmalmgren** [comment]
@barrust Thank you for putting this together and apologies on my slow response to your PR. It somehow slipped through the cracks. Can you rebase this off of master, which now uses `six` for python 3 support?

You may have to make another small change or two to get the tests working properly in python3, but I believe the annoyingness with epub will be fixed.

**Comment by barrust** [comment]
@deanmalmgren Sorry for the slow response. Not a problem. I am currently swamped at work but will get to this as soon as I can. I don't think it should be to large of a delta to get this working.

**Comment by barrust** [comment]
@deanmalmgren Apparently it only required re-basing to get the test to pass; let me know if there are other questions or concerns! 

One thing I was wondering about was the naming convention of the engine selector for audio and image extraction. I didn't think they should be the same name so that one could set optional settings for different file types. Let me know if you would like me to rename the variable to something else.

**Comment by deanmalmgren** [comment]
@barrust thanks for putting this together. I'm on my phone at the moment and will merge this in when I'm back at my computer. In the meantime, what do you mean by "the naming convention of the engine selector for audio and image extraction"?

**Comment by barrust** [comment]
@deanmalmgren Mostly, I am referring to the pdf extraction "method" and for audio I call it the "engine" I am not sure these are the best names but at least they do not collide. I went with a different name, in this case engine, so that someone looping over an entire directory to parse could do something like the following:

``` python
for filename in dir:
   txt = textract.process(filename, method='tesseract', engine='sphinx' )
   print(txt)
```

If they have the same name, then it would be impossible to set different extraction tools for different types. If you have a better convention or name for the audio tool, please, let me know!

**Comment by deanmalmgren** [comment]
@barrust apologies on the slow response with this. Your point about having different keyword arguments for different extraction methods is interesting and a bit unexpected. Great point!! I'm going to start a new issue to discuss different ways of approaching it. 

In the meantime, I'm going to merge this in and clean a few things up. This functionality will be available in the next release!

**Comment by barrust** [comment]
@deanmalmgren This is wonderful! Thank you!

**Pull request merged**
