### PR TITLE
Reduce reliance on chardet-decode...

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by Ousret** [comment]
Hi,

Sorry to barge in, would you be interested in trying an alternative to Chardet?
This project should benefit from it. I am most interested in feedback exchange for the continuous improvement delivery.
See https://charset-normalizer.readthedocs.io/en/latest/why_migrate.html

**Comment by traverseda** [comment]
@Ousret Looks good. I'd welcome a pull request for that, although it wouldn't make it into this release (the last to support python2). I'm hoping to get that release done maybe this weekend if I have time, so if you made a pull request you can expect it to get merged in soon.

**Comment by traverseda** [comment]
@Ousret If I had more free time I'd probably try to move to that library myself. A pull request would be very much appreciated, more reliable unicode detection would be very useful. Definitely something we want.

**Comment by Ousret** [comment]
Here is a PR that keeps BC through py2 and 3 in the meantime. https://github.com/deanmalmgren/textract/pull/395

**Pull request merged**
