### PR TITLE
fix test cases and travis CI

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by traverseda** [comment]
Messed up the PR process a bit while trying to resolve, but not too big of a problem

**Comment by traverseda** [comment]
Well the test cases work now (I accidentally committed the fixes to master on the repo not my fork) but it's failing on what looks like a pep-8 test.

**Comment by traverseda** [comment]
Odd, tests are working locally. I'll take a look at this another day.

Hopefully this should solve a bunch of dependency related issues as we're a lot more liberal in what dependency versions we accept.

**Comment by helder-mattos** [comment]
@traverseda I guess the problem can be fixed with a different approach to installing pip in test environment.
https://github.com/helder-mattos/textract/commit/b68f58414366a78bde541799f6649abf6472007c

But still, the reverted pdfminer version has a missing shebang on the `pdf2txt.py` script file, which causes an error when it's executed.

**Comment by traverseda** [comment]
@helder-mattos thanks!

**Pull request merged**
