### PR TITLE
Change error mode to "ignore" and decrease reliance on chardet.detect() in decoding 

### PR DESCRIPTION
**Pull request by mevers303**
Made it use utf-8 for decoding unless chardet.detect has a certainty level above 80%.  It is often wrong for large PDFs and chooses the wrong charset to decode, and subsequently errors.  Also changed the error mode to 'ignore.'  This makes it much more robust when you know all your documents are going to be in English.

### CODE REVIEW

**Comment by traverseda** [comment]
I suspect this would fix #337 and #338 

Would it make sense to try the `chardet.detect()` method and then fall back to utf-8? or the other way around maybe?

**Comment by traverseda** [comment]
@jpweytjens @deanmalmgren 

Any thoughts on this? Right now textract is failing with the error on a huge amount of content, and it looks like this fixes it. Would be nice to get some insight from someone with commit access.

**Comment by traverseda** [comment]
@mevers303 I'm now a maintainer for textract, if you'd take a second look at this I'd appreciate it.

**Comment by deanmalmgren** [comment]
Sorry I missed the dialog on this one, @traverseda. This seems like a
reasonable approach to me. Thanks for taking care of that one.

**Comment by traverseda** [comment]
No worried, I've merged in equivalent code in #393

**Pull request closed without merging**
